- R/data_match.R
- man/data_match.Rd
- tests/testthat/test-labelled_data.R
> data_match returns data frame

- R/data_match.R
- R/data_remove.R
- R/data_reshape.R
- R/utils_data.R
- tests/testthat/test-center.R
- tests/testthat/test-convert_data_to_numeric.R
- tests/testthat/test-convert_to_na.R
- tests/testthat/test-data_cut.R
- tests/testthat/test-data_extract.R
- tests/testthat/test-data_match.R
- tests/testthat/test-data_merge.R
- tests/testthat/test-data_remove.R
- tests/testthat/test-data_reshape.R
- tests/testthat/test-distributions.R
- tests/testthat/test-labelled_data.R
- tests/testthat/test-standardize-data.R
- tests/testthat/test-std_center.R
- tests/testthat/test-std_center_scale_args.R
- tests/testthat/test-utils_data.R
https://github.com/easystats/easystats/issues/86
> Clean up test conditionals

- NEWS.md
- R/utils_standardize_center.R
- R/weighted_mean_median_sd_mad.R
- man/weighted_mean.Rd
- tests/testthat/test-weighted-stats.R
more verbose is better for the users; similar to sjstats
> rename weights parameter

- R/data_extract.R
- R/data_findcols.R
- R/data_remove.R
- R/data_reshape.R
- R/demean.R
- R/describe_distribution.R
- R/utils.R
https://github.com/easystats/easystats/issues/220
> use insight helpers

- tests/testthat/test-data_reverse.R
I don't know if this should be in NEWS since it has no influence on user experience, let me know
> Add tests for data_reverse()

- R/convert_to_na.R
- R/data_cut.R
- R/data_relocate.R
- R/data_remove.R
- R/data_reverse.R
- R/select_helpers.R
- man/convert_to_na.Rd
- man/data_cut.Rd
- man/data_relocate.Rd
- man/data_rename.Rd
- man/data_rescale.Rd
- man/data_reverse.Rd
- tests/testthat/test-convert_to_na.R
- tests/testthat/test-data_relocate.R
- tests/testthat/test-data_reverse.R
- tests/testthat/test-labelled_data.R
> use "select" and select-helpers for data_relocate and data_reorder

- R/adjust.R
- R/center.R
- R/convert_to_na.R
- R/data_cut.R
- R/data_extract.R
- R/data_findcols.R
- R/data_rescale.R
- R/data_reshape.R
- R/data_reverse.R
- R/normalize.R
- R/ranktransform.R
- R/select_helpers.R
- R/standardize.R
- R/utils_standardize_center.R
- man/center.Rd
- man/convert_to_na.Rd
- man/data_cut.Rd
- man/data_extract.Rd
- man/data_relocate.Rd
- man/data_rename.Rd
- man/data_rescale.Rd
- man/data_reverse.Rd
- man/data_to_long.Rd
- man/normalize.Rd
- man/ranktransform.Rd
- man/standardize.Rd
- tests/testthat/test-data_cut.R
- tests/testthat/test-data_reorder.R
- tests/testthat/test-data_reshape.R
- tests/testthat/test-standardize-data.R
> reshape_longer select helpers

- R/winsorize.R
- tests/testthat/test-center.R
- tests/testthat/test-data_reverse.R
- tests/testthat/test-normalize.R
- tests/testthat/test-ranktransform.R
- tests/testthat/test-standardize-data.R
- tests/testthat/test-winsorization.R
> add some tests

- NEWS.md
- R/data_reshape.R
- man/data_restoretype.Rd
- man/data_to_long.Rd
- tests/testthat/_snaps/data_reshape.md
- tests/testthat/test-data_reshape.R
> Fix column names in data_to_wide()

- .github/workflows/R-check.yaml
- DESCRIPTION
- NEWS.md
- README.Rmd
- README.md
- tests/testthat/test-center.R
- tests/testthat/test-data_reverse.R
- tests/testthat/test-normalize.R
- tests/testthat/test-ranktransform.R
https://github.com/easystats/easystats/issues/240
> Bump needed R version to 3.5

- tests/testthat/test-data_read.R
> Testing data_read: use {circus} data and skip_if_offline

- NEWS.md
- R/data_reshape.R
- man/data_to_wide.Rd
- tests/testthat/test-data_reshape.R
Related to #15.
``` r
library(tidyr)
library(dplyr)
production <- expand_grid(
product = c("A", "B"), 
country = c("AI", "EI"), 
year = 2000:2014
) %>%
filter((product == "A" & country == "AI") | product == "B") %>% 
mutate(production = rnorm(nrow(.)))
production
#> # A tibble: 45 × 4
#>    product country  year production
#>    <chr>   <chr>   <int>      <dbl>
#>  1 A       AI       2000      0.771
#>  2 A       AI       2001     -0.380
#>  3 A       AI       2002      0.233
#>  4 A       AI       2003     -0.677
#>  5 A       AI       2004      1.29 
#>  6 A       AI       2005     -1.60 
#>  7 A       AI       2006     -0.938
#>  8 A       AI       2007     -2.06 
#>  9 A       AI       2008      0.687
#> 10 A       AI       2009      0.203
#> # … with 35 more rows …
```
> data_to_wide: add names_glue

- .github/workflows/render-readme.yml
> use macos for render-readme

- revdep/README.md
- revdep/cran.md
- revdep/problems.md
@strengejacke Lots of breakages 🙈
> revdepcheck

- DESCRIPTION
- NEWS.md
- cran-comments.md
- tests/testthat/test-data_reshape.R
> Fix tests for `{poorman}` update

- R/data_match.R
- tests/testthat/test-data_match.R
> data_filter: move filter check before calling subset()

- .github/workflows/R-CMD-check.yaml
- .github/workflows/html-5-check.yaml
- .github/workflows/pkgdown.yaml
- .github/workflows/render-readme.yaml
- .github/workflows/test-coverage.yaml
https://github.com/easystats/easystats/issues/234
> Use new GHA workflows for easystats

- R/data_match.R
- tests/testthat/test-data_match.R
> data_filter: allow <= and >= 

- vignettes/tidyverse_translation.Rmd
> add data_peek in tidyverse vignette

- R/data_arrange.R
- R/data_partition.R
- R/select_helpers.R
- R/utils.R
- tests/testthat/test-data_partition.R
- tests/testthat/test-utils.R
Also, `data_arrange()` now warns if some columns don't exist in `select` and if `safe = TRUE`
> Add utils for coercing to dataframe

- DESCRIPTION
- NEWS.md
- R/data_read.R
- man/data_read.Rd
- tests/testthat/test-data_read.R
- Adds a `convert_factors` argument, to modify behaviour
- Improves stability of correctly labelling factors when converting to factors
> Improve data_read()

- DESCRIPTION
- NEWS.md
- R/data_to_long.R
- R/data_to_wide.R
- R/utils.R
- tests/testthat/test-data_reshape.R
Before:
``` r
family <- tidyr::tibble(
family = 1:3,
dob_child1 = as.Date(c("1998-11-26", "2004-10-10", "2000-12-05")),
dob_child2 = as.Date(c("2000-01-29", NA, "2004-04-05"))
)
family
#> # A tibble: 3 × 3
#>   family dob_child1 dob_child2
#>    <int> <date>     <date>    
#> 1      1 1998-11-26 2000-01-29
#> 2      2 2004-10-10 NA        
#> 3      3 2000-12-05 2004-04-05
tidyr::pivot_longer(family, !family, names_to = "child")
#> # A tibble: 6 × 3
#>   family child      value     
#>    <int> <chr>      <date>    
#> 1      1 dob_child1 1998-11-26
#> 2      1 dob_child2 2000-01-29
#> 3      2 dob_child1 2004-10-10
#> 4      2 dob_child2 NA        
#> 5      3 dob_child1 2000-12-05
#> 6      3 dob_child2 2004-04-05
datawizard::data_to_long(family, -c("family"), names_to = "child")
#> # A …
```
> Keep date format after reshaping

- DESCRIPTION
- NEWS.md
- R/data_to_long.R
- R/data_to_wide.R
- R/utils.R
- tests/testthat/test-data_reshape.R
Almost identical to #291, fix for R before 4.1.0
> Keep date format after reshaping 

- R/data_to_wide.R
- tests/testthat/test-data_reshape.R
> Fix data_to_wide when only one column

- DESCRIPTION
- NEWS.md
- R/convert_to_na.R
- tests/testthat/test-convert_to_na.R
> Fix `convert_to_na` with date

- DESCRIPTION
- NEWS.md
- R/normalize.R
- man/normalize.Rd
- tests/testthat/test-normalize.R
> normalize(): do not include bounds for beta regression

- DESCRIPTION
- NEWS.md
- R/data_match.R
- R/data_select.R
- R/data_to_long.R
- R/data_to_wide.R
- R/to_numeric.R
- tests/testthat/test-attributes-grouped-df.R
- tests/testthat/test-attributes.R
- tests/testthat/test-get_columns.R
> data.frame methods should preserve attributes

- DESCRIPTION
- NEWS.md
- R/data_codebook.R
- tests/testthat/test-data_codebook.R
> Issues with creating codebook with labelled data

- DESCRIPTION
- NEWS.md
@etiennebacher You should have received an email about CRAN submission.
> CRAN RC 0.6.5

- DESCRIPTION
- NEWS.md
- R/center.R
- R/data_match.R
- R/standardize.R
- R/utils_standardize_center.R
- man/data_match.Rd
- tests/testthat/test-center.R
- tests/testthat/test-standardize-data.R
> Issues in `standardize()` when only providing one of `center`/`scale`

- R/data_match.R
- R/data_partition.R
- R/select_nse.R
> Finish adding `use.names = FALSE` where necessary

- NEWS.md
- cran-comments.md
https://github.com/easystats/workflows/issues/21
> Release 0.7.0

- DESCRIPTION
- NEWS.md
- R/data_merge.R
- tests/testthat/test-data_merge.R
> tibble-issue

- R/select_nse.R
- tests/testthat/test-select_nse.R
> data_select(): add option to evaluate a function passed to `select`

- vignettes/tidyverse_translation.Rmd
> Include new functions in tidyverse vignette

- R/categorize.R
- README.Rmd
- man/categorize.Rd
Be more clear in README about what datawizard does
> Explicit scope in README

- DESCRIPTION
- NEWS.md
- cran-comments.md
> Release 0.12.0

- DESCRIPTION
- NEWS.md
- cran-comments.md
Not running CI here since the only change since 0.12.0 is #525 and all tests already passed there.
> Release 0.12.1

- DESCRIPTION
- NEWS.md
- cran-comments.md
- man/coef_var.Rd
@IndrajeetPatil any comments on the phrasing of CRAN comments before I make a new release? Given the minimal changes, I don't want to wait for revdepcheck.
> Release 0.12.2

- NEWS.md
- R/select_nse.R
> Fix R-devel error due to change in `grep()`

- DESCRIPTION
- inst/WORDLIST
_modelbased_ is about to be submitted, _insight_ and _parameters_ were just updated on CRAN, so we could check whether tests still pass.
> Test of modelbased devel verison

- DESCRIPTION
- NEWS.md
- cran-comments.md
> Release 1.0.1

- DESCRIPTION
- NEWS.md
- R/data_to_wide.R
- tests/testthat/test-data_to_wide.R
> data_to_wide() puts wrong name "out" if only a unique names col

- tests/testthat/test-data_read.R
- tests/testthat/test-data_shift.R
- tests/testthat/test-labelled_data.R
> Remove messages from tests in random order

- DESCRIPTION
- NEWS.md
- cran-comments.md
> Release 1.1.0

- DESCRIPTION
- NEWS.md
- R/demean.R
- inst/WORDLIST
- tests/testthat/test-demean.R
> Fix issue with nested demean
