easystats/datawizard

DESCRIPTION
R/utils_data.R

Remove condition when `var = NULL` in `column_as_rownames()` as this case is already taken into account by sanity checks.
Close #95

remove useless check in column_as_rownames()

---

R/select_helpers.R
tests/testthat/test-select_nse.R

Add NSE for exclude and add tests for `.select_nse`. Some examples:
``` r
foo <- function(data, select = NULL, exclude = NULL) {
datawizard:::.select_nse(select, data, exclude = exclude, ignore_case = FALSE)
}
foo(iris, exclude = starts_with("Petal"))
#> [1] "Sepal.Length" "Sepal.Width"  "Species"
foo(iris, exclude = ends_with("Length"))
#> [1] "Sepal.Width" "Petal.Width" "Species"
foo(iris, exclude = NULL)
#> [1] "Sepal.Length" "Sepal.Width"  "Petal.Length" "Petal.Width"  "Species"
```
<sup>Created on 2022-03-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

Improve select nse

---

NEWS.md
R/data_match.R
README.Rmd
man/data_match.Rd
tests/testthat/test-data_match.R
tests/testthat/test-labelled_data.R

@strengejacke I think you're right, returning the filtered should be default behavior as it's more consistent with the other `data_*` functions. I'll open PRs in the repos (mostly modelbased) where it needs to be fixed according to this (breaking) change, and then we can merge this

data_match: return filtered data by default

---

DESCRIPTION
NEWS.md
R/winsorize.R
man/winsorize.Rd
tests/testthat/_snaps/data_to_numeric.md
tests/testthat/test-winsorization.R
vignettes/standardize_data.Rmd

First attempt(!) at adding the possibility to winsorize based on the MAD, related to #177 & #49 & #47.

Winsorize based on the MAD

---

R/data_reshape.R

Before:
``` r
library(tidyr)
bench::mark(
tidyr = who |> 
pivot_longer(
cols = 5:60,
names_to = c("diagnosis", "gender", "age"),
names_sep = "_",
values_to = "count"
) |>
suppressWarnings(),
datawizard = who %>% 
reshape_longer(
select = 5:60,
names_to = c("diagnosis", "gender", "age"),
names_sep = "_",
values_to = "count"
)
)
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 2 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 tidyr       25.86ms   33.7ms    27.7      40.8MB    20.3 
#> 2 datawizard    2.91s    2.91s     0.344   325.6MB     6.53
```
<sup>Created on 2022-07-27 by the [reprex package](https://reprex.tidyverse.org) …

Improve speed of reshape_longer with names_sep

---

DESCRIPTION
NEWS.md
R/convert_na_to.R
man/convert_na_to.Rd
tests/testthat/test-convert_na_to.R

Closes #214 
``` r
devtools::load_all("D:/OneDrive - UQAM/GitHub/forks/datawizard")
#> ℹ Loading datawizard
df <- data.frame(letters, numbers = 1:26, factors = as.factor(letters))[1:5,]
df[2:3,] <- NA
df
#>   letters numbers factors
#> 1       a       1       a
#> 2    <NA>      NA    <NA>
#> 3    <NA>      NA    <NA>
#> 4       d       4       d
#> 5       e       5       e
convert_na_to(df$letters, replacement = 0)
#> [1] "a" "0" "0" "d" "e"
convert_na_to(df, replace_num = 0,
replace_char = 0,
replace_fac = 0)
#>   letters numbers factors
#> 1       a       1       a
#> 2       0       0       0
#> 3       0       0       0
#> 4       d       4       d
#> 5       e       5       e
convert_na_to(df, replacement = 0)
#>   letters numbers factors
#> 1       a       1       a
#> 2       0 …
```

`convert_na_to` improvements when dealing with character

---

R/data_addprefix.R
man/data_rename.Rd
tests/testthat/test-data_addprefix.R

Forgot this one last time so it's creating a bug in `performance::check_outliers`

add regex to `data_addprefix` for correct use in `performance::check_outliers`

---

R/data_reshape.R

Prepare the benchmark:
``` r
library(tidyr)
df <- fish_encounters 
df$fish <- as.numeric(df$fish)
all_df <- list()
for (i in 1:200) {
all_df[[i]] <- df 
all_df[[i]]$fish <- all_df[[i]]$fish + 20*i
}
all <- tibble::as_tibble(data.table::rbindlist(all_df))
```
Current results:
```r
bench::mark(
datawizard = all %>% reshape_wider(names_from = "station", values_from = "seen")
)
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 1 × 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 datawizard    478ms    485ms      2.06      26MB     20.6
```
New results:
``` r
bench::mark(
datawizard = all %>% reshape_wider(names_from = "station", values_from = …
```

data_to_wide: improve speed

---

R/data_reshape.R

Improve speed when using `names_pattern`. 
Current results:
``` r
library(tidyr)
bench::mark(
reshape_longer = who %>%
reshape_longer(
select = 5:60,
names_to = c("diagnosis", "gender", "age"),
names_pattern = "new_?(.*)_(.)(.*)",
values_to = "count"
)
)
#> Warning: Some expressions had a GC in every iteration; so filtering is disabled.
#> # A tibble: 1 × 6
#>   expression          min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>     <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 reshape_longer    3.56s    3.56s     0.281     768MB     4.21
```
New results:
``` r
library(tidyr)
bench::mark(
reshape_longer = who %>%
reshape_longer(
select = 5:60,
names_to = c("diagnosis", "gender", "age"),
names_pattern = "new_?(.*)_(.)(.*)",
values_to …
```

data_to_long: improve speed with names_pattern

---

NEWS.md
R/data_merge.R
R/demean.R
tests/testthat/test-data_merge.R
tests/testthat/test-demean.R

The default behavior of `data_merge()` when `by` columns are not present in both datasets is to warn the user and use all columns that are in both datasets to merge them (even if they are not specified in `by` originally).
This is really odd to me, I don't see when this behavior would be desired. I think an error would be more appropriate (which is the behavior in merge functions of dplyr btw).

Add some tests for demean and data_merge

---

DESCRIPTION
NEWS.md
R/convert_to_na.R
R/data_find.R
R/select_helpers.R
man/adjust.Rd
man/categorize.Rd
man/center.Rd
man/convert_na_to.Rd
man/convert_to_na.Rd
man/data_extract.Rd
man/data_group.Rd
man/data_peek.Rd
man/data_relocate.Rd
man/data_rename.Rd
man/data_tabulate.Rd
man/data_to_long.Rd
man/describe_distribution.Rd
man/find_columns.Rd
man/normalize.Rd
man/ranktransform.Rd
man/recode_values.Rd
man/rescale.Rd
man/reverse.Rd
man/slide.Rd
man/standardize.Rd
man/to_factor.Rd
man/to_numeric.Rd
tests/testthat/test-find_columns.R

Mentioned in the discussion in #258. Examples:
``` r
find_columns(iris, starts_with("Petal", "Sep"))
#> [1] "Sepal.Length" "Sepal.Width"  "Petal.Length" "Petal.Width"
find_columns(iris, ends_with("Length", "Width"))
#> [1] "Sepal.Length" "Sepal.Width"  "Petal.Length" "Petal.Width"
find_columns(iris, contains("et", "idt"))
#> [1] "Sepal.Width"  "Petal.Length" "Petal.Width"
```
<sup>Created on 2022-09-08 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Allow several patterns in select helpers

---

DESCRIPTION
NEWS.md
R/select_helpers.R
tests/testthat/test-data_relocate.R
tests/testthat/test-data_remove.R
tests/testthat/test-find_columns.R
tests/testthat/test-get_columns.R
tests/testthat/test-select_nse.R

Close #258. This PR changes the behavior of select and exclude when there's a minus sign in front of numeric values.
Previously: select the columns starting from the right of the dataset (inconsistent with the behavior of the "-" with other selections).
Now: remove the columns.
``` r
find_columns(iris, -c("Sepal.Length", "Petal.Width"))
#> [1] "Sepal.Width"  "Petal.Length" "Species"
find_columns(iris, -1)
#> [1] "Sepal.Width"  "Petal.Length" "Petal.Width"  "Species"
find_columns(iris, -1:2)
#> Error: You can't mix negative and positive numeric indices in `select` or
#>   `exclude`.
find_columns(iris, -(1:2))
#> [1] "Petal.Length" "Petal.Width"  "Species"
find_columns(iris, -c(1, 3))
#> [1] "Sepal.Width" "Petal.Width" "Species"
find_columns(iris, -starts_with("Sepal", …
```

Selection: using "-" sign with numeric indices removes the columns

---

R/select_helpers.R

Close #267. 
When `select = starts_with(i)` where `i` is an object in a loop or a custom function, we need to find the value of `i`. Basically, this is done by checking the error message that appears when we try to evaluate `starts_with(i)`. Either the error is something like 'xxx doesn't exist", or it is an error due to `tidyselect` (when a package using it is loaded) because select helpers "have to be used within a *select* environment". 
Apparently there were some slight changes in error messages generated by `tidyselect` dev version, so we didn't catch it anymore.

Fix select_helpers with dev version of `tidyselect`

---

R/categorize.R
R/data_rescale.R
R/data_reverse.R
R/data_tabulate.R
R/normalize.R
R/ranktransform.R
R/unstandardize.R
R/utils_standardize_center.R

We have had compatibility for `grouped_df()` methods for dplyr < 0.8 - I think we can remove this and only rely on the structure of grouped df's used since dplyr 0.8 and higher.
no tests needed.

remove dplyr < 0.8 code chunks

---

R/remove_empty.R

Didn't have time to mention it in #275 before it was merged but we can improve the perf of `empty_rows()`:
``` r
empty_rows <- function(x) {
if ((!is.matrix(x) && !is.data.frame(x)) || nrow(x) < 2) {
vector("numeric")
} else {
which(rowSums(is.na(x) | apply(x, c(1, 2), function(i) nchar(as.character(i)) == 0)) == ncol(x))
}
}
new_empty_rows <- function(x) {
if ((!is.matrix(x) && !is.data.frame(x)) || nrow(x) < 2) {
vector("numeric")
} else {
which(apply(x, 1, function(i) all(is.na(i) | nchar(as.character(i)) == 0)))
}
}
tmp <- data.frame(
a = c(1, 2, 3, NA, 5),
b = c("", NA, "", NA, ""),
c = c(NA, NA, NA, NA, NA),
d = c(1, NA, 3, NA, 5),
e = c("", "", "", "", ""),
f = factor(c("", "", "", "", "")),
g = factor(c("", NA, "", NA, "")),
stringsAsFactors = FALSE
)
out <- list()
for (i in …
```

Improve performance of empty_rows()

---

DESCRIPTION
NEWS.md
R/data_arrange.R
R/utils.R
tests/testthat/test-utils.R

No need to waste time if data is already sorted. This can save some time on large datasets but only works when there's only one variable used to arrange the data

`data_arrange`: return data early if already sorted

---

NEWS.md
R/categorize.R
R/data_merge.R
R/data_relocate.R
R/data_remove.R
R/data_rotate.R
R/remove_empty.R
R/utils.R
tests/testthat/test-data_relocate.R
tests/testthat/test-data_remove.R
tests/testthat/test-data_reorder.R

Some functions should be fast whatever the size of the dataframe, such as `data_relocate()` or `data_reorder()` since it's just about moving columns. However, the way attributes are applied back to the modified dataframe leads to a loss of performance because it also reallocates the row names (see [this SO answer](https://stackoverflow.com/questions/74029805/why-does-adding-attributes-to-a-dataframe-take-longer-with-large-dataframes)). When there are millions of rows, this takes some time. Therefore, we should only reallocate the attributes that are "unusual" for a dataframe. This is done in `.replace_attrs()`.
Current (takes more time for large dataset but it shouldn't):
``` r
tmp <- data.frame(x = sample(1:10, size = 2, replace = TRUE),
y = sample(1:10, size = 2, …
```

Modify attributes replacement for performance gains

---

DESCRIPTION
R/data_to_wide.R
R/utils.R
tests/testthat/test-data_reshape.R

The example below causes an error because `data.frame()` adds an "X" in front of column names if they start with a number, so I remove this behavior
Before:
``` r
percentages <- tidyr::tibble(
year = c(2018, 2019, 2020, 2020),
type = factor(c("A", "B", "A", "B"), levels = c("A", "B")),
percentage = c(100, 100, 40, 60)
)
percentages
#> # A tibble: 4 × 3
#>    year type  percentage
#>   <dbl> <fct>      <dbl>
#> 1  2018 A            100
#> 2  2019 B            100
#> 3  2020 A             40
#> 4  2020 B             60
tidyr::pivot_wider(
percentages,
names_from = c(year, type),
values_from = percentage,
)
#> # A tibble: 1 × 4
#>   `2018_A` `2019_B` `2020_A` `2020_B`
#>      <dbl>    <dbl>    <dbl>    <dbl>
#> 1      100      100       40       60
datawizard::data_to_wide(
percentages, …
```

data_to_wide: remove check names

---

R/data_to_wide.R
tests/testthat/test-data_reshape.R

Related to #293. The rewriting I did in reshaping functions starts to become a mess, I will try to improve it later but at least the example is now fixed.
@IndrajeetPatil if the tests pass, then I'm ok to make the release with the patch for R-devel. I found other situations where the reshaping functions don't match 100% the output of `tidyr` (see #293) but our previous reshaping functions also failed so it's not due to the rewriting. I can take care of these later.

Fix failing case in `data_to_wide`

---

DESCRIPTION
NEWS.md
R/data_to_wide.R
tests/testthat/test-data_reshape.R

`data_to_wide`: drop cols that are not in `id_cols` (if specified), `names_from` or `values_from`

---

R/data_tabulate.R
tests/testthat/test-data_tabulate.R

Closes #315
``` r
datawizard::data_tabulate(openintro::military$grade)
#> openintro::military$grade <categorical>
#> # total N=1,414,593 valid N=1,414,593
#> 
#> Value           |         N | Raw % | Valid % | Cumulative %
#> ----------------+-----------+-------+---------+-------------
#> enlisted        | 1,183,889 | 83.69 |   83.69 |        83.69
#> officer         |   211,525 | 14.95 |   14.95 |        98.64
#> warrant officer |    19,179 |  1.36 |    1.36 |       100.00
#> <NA>            |         0 |  0.00 |    <NA> |         <NA>
```
<sup>Created on 2022-11-15 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Add big mark also to counts in headers

---

DESCRIPTION
NEWS.md
R/utils_standardize_center.R
tests/testthat/test-center.R

Close #324
``` r
x <- 1:4
M <- mean(x)
center(x, center = M)
#> [1] -1.5 -0.5  0.5  1.5
#> attr(,"center")
#> [1] 2.5
#> attr(,"scale")
#> [1] 1
#> attr(,"robust")
#> [1] FALSE
center(100, center = M)
#> [1] 97.5
#> attr(,"center")
#> [1] 2.5
#> attr(,"scale")
#> [1] 1
#> attr(,"robust")
#> [1] FALSE
center(100)
#> The variable contains only one unique value and will be set to 0.
#> [1] 0
#> attr(,"center")
#> [1] 100
#> attr(,"scale")
#> [1] 1
#> attr(,"robust")
#> [1] FALSE
```
@mattansb can you confirm this is the expected behavior (and check the tests)?

Fix `center()` when only one value and `reference` or `center` specified

---

R/categorize.R
R/demean.R
tests/testthat/test-attributes.R
tests/testthat/test-center.R
tests/testthat/test-convert_to_na.R
tests/testthat/test-data_cut.R
tests/testthat/test-data_merge.R
tests/testthat/test-data_read.R
tests/testthat/test-data_rename.R
tests/testthat/test-data_reverse.R
tests/testthat/test-data_to_long.R
tests/testthat/test-data_to_wide.R
tests/testthat/test-data_unique.R
tests/testthat/test-demean.R
tests/testthat/test-normalize.R
tests/testthat/test-ranktransform.R

Close #344 
Mostly just add `verbose = FALSE` or sth equivalent. Please take a look at `test-data_cut.R` to be sure the behavior is correct (it currently prints 2 different messages for `NA` and `NA_real_`)

Silence the messages in tests

---

DESCRIPTION
NEWS.md
R/remove_empty.R
tests/spelling.R
tests/testthat/test-empty-dataframe.R

Close #349 
``` r
options(warn = 2L)
load("test.RData")
datawizard::remove_empty(out)
#>                Parameter     Median   CI     CI_low    CI_high pd   Component
#> 1                     mu 64.6462056 0.95 61.9670930 67.3660318  1       extra
#> 2             complaints  0.7245799 0.95  0.5067928  0.9187746  1       extra
#> 3                   sig2 52.2962092 0.95 31.5455269 92.1527877  1       extra
#> 4                      g  1.3570011 0.95  0.1953671 38.2999735  1       extra
#> 5        advance-advance         NA   NA         NA         NA NA conditional
#> 6  complaints-complaints         NA   NA         NA         NA NA conditional
#> 7      critical-critical         NA   NA         NA         NA NA conditional
#> 8      learning-learning         NA   NA …
```

Fix `empty_columns` with only `NA_character_`

---

DESCRIPTION
NEWS.md
R/winsorize.R
man/winsorize.Rd
tests/testthat/test-winsorization.R

Close #357 
New behavior:
``` r
winsorize(1:3, threshold = 1.2)
#> Error: `threshold` for winsorization must be a scalar between 0 and 0.5.
```

`winsorize`: change warnings to errors

---

DESCRIPTION
NEWS.md
R/convert_na_to.R
R/data_relocate.R
R/data_rotate.R
R/data_to_long.R
R/data_to_wide.R
R/ranktransform.R
R/select_nse.R
man/data_relocate.Rd
man/data_rotate.Rd
man/data_to_long.Rd
man/data_to_wide.Rd
man/ranktransform.Rd
tests/testthat/test-convert_na_to.R
tests/testthat/test-standardize_models.R

Close #352 . 
The code of `convert_na_to.data.frame()` is now much simpler. This also fixes an unexpected warning about unknown variables.
``` r
test_df <- data.frame(
x = c(1, 2, NA),
x2 = c(4, 5, NA),
y = c("a", "b", NA)
)
test_df
#>    x x2    y
#> 1  1  4    a
#> 2  2  5    b
#> 3 NA NA <NA>
convert_na_to(
test_df,
replace_num = 0,
select = list(x2 = 1)
)
#>   x x2    y
#> 1 1  4    a
#> 2 2  5    b
#> 3 0  1 <NA>
```

Refactor `convert_na_to`

---

R/center.R
R/data_rescale.R
R/normalize.R
R/standardize.R
tests/testthat/test-center.R
tests/testthat/test-data_rescale.R
tests/testthat/test-normalize.R
tests/testthat/test-standardize-data.R

#408
This PR doesn't fix 408, but we don't need the class attribute for data frame methods, so we can remove it and thereby reduce possible issues we do not yet anticpate.

dw_transformer hits again

---

DESCRIPTION
NEWS.md
R/describe_distribution.R
tests/testthat/test-describe_distribution.R

Close #421 
``` r
describe_distribution(iris$Species)
#> Mean | SD |               Range | Skewness | Kurtosis |   n | n_Missing
#> -----------------------------------------------------------------------
#>      |    | [setosa, virginica] |        0 |    -1.51 | 150 |         0
describe_distribution(iris, select = "Species")
#> NULL
```

Fix error in dataframe method of `describe_distribution()`

---

tests/testthat/test-standardize_models.R

Close #425 
For some reason, this `brms` test fails on macOS. Maybe this could be reported to the `brms` repo but I can't do it (I don't have macOS)

Test macos failure

---

DESCRIPTION
NEWS.md
R/recode_into.r
man/recode_into.Rd
tests/testthat/test-recode_into.R

`recode_into()` by defaults overwrite former recodings when multiple recode patterns apply. This PR adds an `overwrite` argument that allows users to skip this behaviour, preserving already recoded cases and not overwrite them.
``` r
x <- 1:30
recode_into(
x > 1 ~ "a",
x > 10 & x <= 15 ~ "b",
default = "c"
)
#> Warning: Several recode patterns apply to the same cases. Some of the already
#>   recoded cases will be overwritten with new values again (e.g. pattern 2
#>   overwrites the former recode of case 1).
#>   Please check if this is intentional!
#>  [1] "c" "a" "a" "a" "a" "a" "a" "a" "a" "a" "b" "b" "b" "b" "b" "a" "a" "a" "a"
#> [20] "a" "a" "a" "a" "a" "a" "a" "a" "a" "a" "a"
recode_into(
x > 1 ~ "a",
x > 10 & x <= 15 ~ "b",
default = "c",
overwrite = FALSE
)
#> …
```

recode_into can skip overwriting former recodes

---

DESCRIPTION
NEWS.md
R/recode_into.r
tests/testthat/test-recode_into.R

Was:
```r
x <- 1:10
recode_into(
x >= 3 & x <= 7 ~ 1,
x > 5 ~ 2,
default = 0
)
#> Warning: Several recode patterns apply to the same cases. Some of the already
#>   recoded cases will be overwritten with new values again (e.g. pattern 2
#>   overwrites the former recode of case 1).
#>   Please check if this is intentional!
#>  [1] 0 0 1 1 1 2 2 2 2 2
```
Should print "case 6" actually.

fix wrong case number in warning

---

DESCRIPTION
NEWS.md
R/data_match.R
tests/testthat/test-data_match.R

was:
``` r
d <- data.frame(
a = c("aa", "a1", "bb", "b1", "cc", "c1"),
b = 1:6,
stringsAsFactors = FALSE
)
data_filter(d, grep("^[A-Za-z][0-9]$", x = d$a))
#> Error: Filtering did not work. Please check if you need `==` (instead of `=`)
#>   for comparison.
```
now is:
``` r
data_filter(d, grep("^[A-Za-z][0-9]$", x = d$a))
#>    a b
#> 2 a1 2
#> 4 b1 4
#> 6 c1 6
```
<sup>Created on 2023-06-28 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

fix for functions

---

DESCRIPTION
NEWS.md
R/data_write.R
tests/testthat/test-data_write.R

@etiennebacher We should merge this fix before submiting _datawizard_.

Fix `data_write()` for partially labelled characters

---

tests/testthat/test-data_write.R

Use `withr` in tests of `data_write()`

---

.lintr
DESCRIPTION
NEWS.md
R/data_reverse.R
R/to_numeric.R
R/utils_labels.R
tests/testthat/test-data_to_numeric.R
tests/testthat/test-standardize_models.R

``` r
x <- factor(c(1, 2, 3, 4))
x <- assign_labels(x, values = c("one", "two", "three", "four"))
to_numeric(x, dummy_factors = FALSE)
#> [1] 1 2 3 4
#> attr(,"labels")
#>   one   two three  four 
#>     1     2     3     4
to_numeric(reverse_scale(x), dummy_factors = FALSE)
#> [1] 4 3 2 1
#> attr(,"labels")
#>   one   two three  four 
#>     4     3     2     1
```
<sup>Created on 2023-12-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Preserve correct label oder

---

DESCRIPTION
NEWS.md
R/data_modify.R
R/normalize.R
man/data_modify.Rd
man/datawizard-package.Rd
tests/testthat/test-data_modify.R

``` r
data(iris)
d <- iris[1:5, ]
data_modify(d, .at = "Species", .modify = as.numeric)
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#> 1          5.1         3.5          1.4         0.2       1
#> 2          4.9         3.0          1.4         0.2       1
#> 3          4.7         3.2          1.3         0.2       1
#> 4          4.6         3.1          1.5         0.2       1
#> 5          5.0         3.6          1.4         0.2       1
data_modify(d, .if = is.factor, .modify = as.numeric)
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#> 1          5.1         3.5          1.4         0.2       1
#> 2          4.9         3.0          1.4         0.2       1
#> 3          4.7         3.2          1.3         0.2       1
#> 4 …
```

data_modify() gains .it and .at

---

DESCRIPTION
NEWS.md
R/data_modify.R
R/data_tabulate.R
man/data_tabulate.Rd
man/datawizard-package.Rd
tests/testthat/_snaps/data_tabulate.md
tests/testthat/test-data_tabulate.R

``` r
data(efc, package = "datawizard")
set.seed(123)
efc$weights <- abs(rnorm(n = nrow(efc), mean = 1, sd = 0.5))
data_tabulate(efc$e42dep)
#> elder's dependency (efc$e42dep) <categorical>
#> # total N=100 valid N=97
#> 
#> Value |  N | Raw % | Valid % | Cumulative %
#> ------+----+-------+---------+-------------
#> 1     |  2 |  2.00 |    2.06 |         2.06
#> 2     |  4 |  4.00 |    4.12 |         6.19
#> 3     | 28 | 28.00 |   28.87 |        35.05
#> 4     | 63 | 63.00 |   64.95 |       100.00
#> <NA>  |  3 |  3.00 |    <NA> |         <NA>
data_tabulate(efc$e42dep, weights = efc$weights)
#> elder's dependency (efc$e42dep) <categorical>
#> # total N=105 valid N=100
#> 
#> Value |  N | Raw % | Valid % | Cumulative %
#> ------+----+-------+---------+-------------
#> …
```

`data_tabulate()` gains a `weights` argument

---

DESCRIPTION
R/data_tabulate.R
R/data_xtabulate.R
tests/testthat/test-data_tabulate.R

```r
data(efc, package = "datawizard")
set.seed(123)
efc$weights <- abs(rnorm(n = nrow(efc), mean = 1, sd = 0.5))
data_tabulate(efc$c172code, weights = efc$wweight)
```

Check if "weights" exists for vector-method

---

DESCRIPTION
NEWS.md
R/recode_into.R
tests/testthat/test-recode_into.R

``` r
data(mtcars)
x1 <- recode_into(
mpg > 10 ~ 1,
gear == 5 ~ NA_real_,
data = mtcars
)
#> Warning: Several recode patterns apply to the same cases. Some of the already
#>   recoded cases will be overwritten with new values again (e.g. pattern 2
#>   overwrites the former recode of case 27).
#>   Please check if this is intentional!
x2 <- recode_into(
mpg > 10 ~ 1,
gear == 5 ~ NA,
data = mtcars
)
#> Warning: Several recode patterns apply to the same cases. Some of the already
#>   recoded cases will be overwritten with new values again (e.g. pattern 2
#>   overwrites the former recode of case 27).
#>   Please check if this is intentional!
identical(x1, x2)
#> [1] TRUE
```
<sup>Created on 2024-05-04 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

DOn't check type of NA values

---

DESCRIPTION
NEWS.md
R/data_select.R
R/extract_column_names.R
R/row_means.R
R/select_nse.R
R/to_factor.R
R/unnormalize.R
man/extract_column_names.Rd
tests/testthat/test-data_select.R

``` r
data(mtcars)
data_select(mtcars, c(neu = "mpg", alt = "cyl", hoho = "wt")) |> head()
#>                    neu alt  hoho
#> Mazda RX4         21.0   6 2.620
#> Mazda RX4 Wag     21.0   6 2.875
#> Datsun 710        22.8   4 2.320
#> Hornet 4 Drive    21.4   6 3.215
#> Hornet Sportabout 18.7   8 3.440
#> Valiant           18.1   6 3.460
```
``` r
data_select(mtcars, c(neu = "mpg", "cyl", hoho = "wt")) |> head()
#>                    neu cyl  hoho
#> Mazda RX4         21.0   6 2.620
#> Mazda RX4 Wag     21.0   6 2.875
#> Datsun 710        22.8   4 2.320
#> Hornet 4 Drive    21.4   6 3.215
#> Hornet Sportabout 18.7   8 3.440
#> Valiant           18.1   6 3.460
```
<sup>Created on 2024-06-07 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

Allow named character vector in `select`, to rename variables

---

DESCRIPTION
vignettes/tidyverse_translation.Rmd

https://www.r-project.org/nosvn/R.check/r-oldrel-macos-x86_64/datawizard-00check.html

Fix CRAN errors

---

vignettes/tidyverse_translation.Rmd

Hopefully, this slightly improves the setup chunk code, irrespective of whether it solves #527 or not.

Minor clean-up translation vignette setup

---

.Rbuildignore
pkgdown/_pkgdown.yaml
vignettes/overview_of_vignettes.Rmd

Put vignettes in `.Rbuildignore`

---

DESCRIPTION
NEWS.md
R/demean.R
inst/WORDLIST
man/demean.Rd
tests/testthat/test-demean.R

degroup() for nested models

---

DESCRIPTION

See discussion in https://github.com/easystats/insight/pull/936.
This NOTE was already on win-builder, but I didn't realize. I now uploaded _insight_ to win-builder again, removing Twitter IDs. If this resolves the NOTE, we can merge this PR (it's likely to cause the same problems with _datawizard_ then).

Remove Twitter-tag from Authors@R

---

R/to_numeric.R
man/datawizard-package.Rd
man/to_numeric.Rd
tests/testthat/_snaps/data_to_numeric.md
tests/testthat/test-data_to_numeric.R

Default values of `to_numeric()`

---

DESCRIPTION
NEWS.md
R/describe_distribution.R
tests/testthat/test-describe_distribution.R

Close #540
``` r
set.seed(123456)
describe_distribution(mtcars[mtcars$cyl=="6",], wt, centrality = "map", ci = 0.95)
#> Warning: When bootstrapping CIs, sample was too sparse to find TD. Returning NA
#>   for CIs.
#> Variable |  MAP |  IQR | 95% CI |        Range | Skewness | Kurtosis | n | n_Missing
#> ------------------------------------------------------------------------------------
#> wt       | 3.43 | 0.67 |        | [2.62, 3.46] |    -0.36 |    -2.08 | 7 |         0
```
<sup>Created on 2024-10-07 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

Do not error when bootstrapping CIs if sample is too sparse

---

DESCRIPTION
NEWS.md
R/data_group.R
R/data_match.R
man/data_match.Rd
tests/testthat/test-data_match.R

Rename `drop_na` into `remove_na` in `data_match()`

---

DESCRIPTION
NEWS.md
R/data_read.R
tests/testthat/test-data_read.R

We had this already for `rds`, but forgot for `RData`.

set `trust = TRUE` also for RData files

---

DESCRIPTION
NEWS.md
R/data_read.R
man/data_read.Rd
tests/testthat/test-data_read.R

Need to add tests.
Behaviour of  older datawizard versions (see column `agecat`):
``` r
d <- datawizard::data_read("https://github.com/vincentarelbundock/marginaleffects/raw/refs/heads/main/vignettes/chapters/data/hiv.rds")
#> Reading data...
#> Variables where all values have associated labels are now converted into
#>   factors. If this is not intended, use `convert_factors = FALSE`.
#> 0 out of 8 variables were fully labelled and converted into factors.
str(d)
#> 'data.frame':    2884 obs. of  8 variables:
#>  $ village  : num  43 117 2 6 11 14 15 25 37 100 ...
#>  $ outcome  : num  1 0 0 0 0 0 1 0 1 0 ...
#>  $ distance : num  0.549 0.84 3.342 2.323 1.386 ...
#>  $ amount   : num  0 0 0 0 0 0 0 0 0 0 ...
#>  $ incentive: num  0 0 0 0 0 0 0 0 0 0 ...
#>  $ age      : num  14 14 15 15 …
```

`data_read()` preserves class for rds files

---

DESCRIPTION
R/standardize.models.R
tests/testthat/test-standardize_models.R

The message when standardizing failed due to "problematic formulas" was not always clear. Now it should be clearer to users why model cannot be standardized.
Inspired by this SO post: https://stackoverflow.com/questions/79207876/variable-names-and-easystats-reports
``` r
data(mtcars)
m <- lm(mpg ~ hp, data = mtcars)
datawizard::standardise(m)
#> 
#> Call:
#> lm(formula = mpg ~ hp, data = data_std)
#> 
#> Coefficients:
#> (Intercept)           hp  
#>  -3.149e-17   -7.762e-01
colnames(mtcars)[1] <- "1_mpg"
m <- lm(`1_mpg` ~ hp, data = mtcars)
datawizard::standardise(m)
#> Warning: Looks like you are using invalid syntactically variables names, quoted
#>   in backticks: `1_mpg`. This may result in unexpected behaviour. Please
#>   rename your variables (e.g., `X1_mpg` instead of `1_mpg`) …
```

Warn user for invalid formula

---

DESCRIPTION
NEWS.md
R/data_rename.R
man/categorize.Rd
man/data_match.Rd
man/data_merge.Rd
man/data_partition.Rd
man/data_relocate.Rd
man/data_rename.Rd
man/data_rotate.Rd
man/data_to_long.Rd
man/data_to_wide.Rd
man/extract_column_names.Rd
man/recode_values.Rd
man/slide.Rd
man/text_format.Rd
man/winsorize.Rd
tests/testthat/test-data_rename.R

``` r
head(data_rename(mtcars[1:3], c("mpg", "cyl", "disp"), "formerly_{col}"))
#>                   formerly_mpg formerly_cyl formerly_disp
#> Mazda RX4                 21.0            6           160
#> Mazda RX4 Wag             21.0            6           160
#> Datsun 710                22.8            4           108
#> Hornet 4 Drive            21.4            6           258
#> Hornet Sportabout         18.7            8           360
#> Valiant                   18.1            6           225
head(data_rename(mtcars[1:3], c("mpg", "cyl", "disp"), "{col}_is_column_{n}"))
#>                   mpg_is_column_1 cyl_is_column_2 disp_is_column_3
#> Mazda RX4                    21.0               6              160
#> Mazda RX4 Wag                21.0               6 …
```

Allow glue-styled pattern for `data_rename()`

---

DESCRIPTION
R/adjust.R
R/data_rename.R
R/data_rescale.R
R/data_rotate.R
R/data_to_long.R
R/select_nse.R
man/adjust.Rd
man/data_partition.Rd
man/data_rename.Rd
man/data_to_long.Rd
man/rescale.Rd
tests/testthat/test-data_rename.R

`data_rename()`: "Error: Following variable(s) were not found" in version '0.13.0.17'

---

DESCRIPTION
NEWS.md
R/ranktransform.R
man/ranktransform.Rd
tests/testthat/test-ranktransform.R

Close #570. @mattansb can you double check this? 
I also noticed there are no tests for the `method` argument. I think this came from `effectsize` so if you already have a suite of tests for this, we could add it here.

New argument `zeros` in `ranktransform()`

---

DESCRIPTION
NEWS.md
R/demean.R
man/demean.Rd
tests/testthat/_snaps/demean.md
tests/testthat/test-demean.R

Append results of `demean()` to original df?

---

R/data_rename.R
R/data_xtabulate.R
R/select_nse.R
R/smoothness.R
R/standardize.models.R
man/data_rename.Rd

https://github.com/easystats/datawizard/issues/576#issuecomment-2569583348

`data_rename`: mention use of `unlist()` for named lists

---

DESCRIPTION
NEWS.md
R/data_codebook.R
tests/testthat/test-data_codebook.R

Was:
``` r
data(iris)
datawizard::data_codebook(iris, select = starts_with("abc"))
#> Error in names(out) <- replace(names(out), names(out) == pattern[i], replacement[i]): attempt to set an attribute on NULL
```
Is:
``` r
data(iris)
datawizard::data_codebook(iris, select = starts_with("abc"))
#> Warning: No column names that matched the required search pattern were found.
#> NULL
```

Give informative error in `data_codebook()` when `select` matched no variables.

---

DESCRIPTION
NEWS.md
R/data_codebook.R
R/data_to_long.R
man/data_to_long.Rd
tests/testthat/test-data_to_long.R

Not sure if there's a reason why we set `verbose = FALSE` when we call `.select_nse()` inside `data_to_long()`, but today during teaching, I realized that the spell-checker is helpful in identifying typos. I suggest we add a `verbose` option.

Raise an error when `data_to_long()` uses unknown variables

---

DESCRIPTION
NEWS.md
R/data_read.R
inst/WORDLIST
tests/testthat/test-data_read.R

@DominiqueMakowski This was the issue I was facing when downloading chocominimodel with `data_read()`. It tries to coerce data into a data frame, if possible. And it is possible with stan models. Thus, this PR implements a better check, so you can also download models from internet using `data_read()`.

`data_read()` no longer coerces Stan models into data frames.

---

DESCRIPTION
NEWS.md
R/describe_distribution.R
tests/testthat/test-data_recode.R
tests/testthat/test-describe_distribution.R

Drop empty group combinations in `describe_distribution()`

---

DESCRIPTION
NEWS.md
R/describe_distribution.R
R/format.R
tests/testthat/_snaps/describe_distribution.md
tests/testthat/helper-state.R
tests/testthat/test-describe_distribution.R

Fixes #599.
Here's what I get with a quarto HTML output (on two variables only):
```r
palmerpenguins::penguins |>
group_by(species) |>
describe_distribution(select = c("bill_length_mm", "bill_depth_mm")) |>
insight::display()
palmerpenguins::penguins |>
group_by(species, island) |>
describe_distribution(select = c("bill_length_mm", "bill_depth_mm")) |>
insight::display()
```
@profandyfield @strengejacke @DominiqueMakowski is this what you'd like?

Rework formatted output of `describe_distribution()`

---

DESCRIPTION
NEWS.md
R/data_modify.R
man/data_modify.Rd
tests/testthat/_snaps/data_modify.md
tests/testthat/test-data_modify.R
vignettes/tidyverse_translation.Rmd

```r
data_modify(iris, as_expression("sepwid = 2 * Sepal.Width")) |> head()
data_modify(
iris,
as_expression(c("sepwid = 2 * Sepal.Width", "seplen = 5 * Sepal.Length"))
) |> head()
data_modify(iris, sepwid = as_expression("2 * Sepal.Width")) |> head()
data_modify(
iris,
sepwid = as_expression("2 * Sepal.Width"),
seplen = {"5 * Sepal.Length"}
) |> head()
e <- "sepwid = 2 * Sepal.Width"
data_modify(iris, as_expression(e)) |> head()
e <- c("sepwid = 2 * Sepal.Width", "seplen = 5 * Sepal.Length")
data_modify(iris, as_expression(e)) |> head()
e <- "2 * Sepal.Width"
data_modify(iris, sepwid = as_expression(e)) |> head()
e <- "2 * Sepal.Width"
data_modify(iris, sepwid = as_expression(e), seplen = 5 * Sepal.Length) |> head()
e <- "2 * Sepal.Width"
f <- "half_petal = 0.5 * …
```

New handling of expressions in `data_modify()`, introducing `as_expr()` helper function

---

DESCRIPTION
NEWS.md
R/data_to_wide.R
tests/testthat/test-data_to_wide.R

This example currently fails, which is fixed by this PR.
```r
long_df <- data.frame(
subject_id = c(1, 1, 2, 2, 3, 5, 4, 4),
time = rep(c(1, 2), 4),
score = c(10, NA, 15, 12, 18, 11, NA, 14),
anxiety = c(5, 7, 6, NA, 8, 4, 5, NA)
)
data_to_wide(long_df,
id_cols = "subject_id",
names_from = "time",
values_from = c("score", "anxiety")
)
```

Fix `data_to_wide()` on unbalanced panel with multiple variables in `values_from` 

---

DESCRIPTION
NEWS.md
R/data_to_wide.R
man/data_to_wide.Rd
tests/testthat/test-data_to_wide.R
vignettes/tidyverse_translation.Rmd

- No longer removes widened columns when these were NA only
- Remove `values_fill` argument, as this never worked as probably intended
- allow select-helpers for `values_from`
- validate input arguments
This one replaces #645

`data_to_wide()`: disable arg `values_fill`, do not drop empty columns, allow select helpers

---

DESCRIPTION
R/data_match.R
R/data_modify.R
R/select_nse.R

Both when evaluation succeeds or fails, `tryCatch()` is faster than `try()`. This can be beneficial when we have repeated calls to function, e.g. for grouped data frames.
``` r
microbenchmark::microbenchmark(
try(x <- 1, silent = TRUE),
tryCatch(x <- 1, error = function(e) NULL),
times = 1000
)
#> Unit: microseconds
#>                                        expr   min    lq     mean median    uq
#>                  try(x <- 1, silent = TRUE) 6.100 6.401 7.846637  6.601 7.101
#>  tryCatch(x <- 1, error = function(e) NULL) 5.701 6.001 7.157679  6.201 6.700
#>      max neval cld
#>  220.501  1000  a 
#>   58.600  1000   b
microbenchmark::microbenchmark(
try(x <- a, silent = TRUE),
tryCatch(x <- a, error = function(e) NULL),
times = 1000
)
#> Unit: microseconds
#> …
```

Improve performance by using `tryCatch()` instead of `try()`
